import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { io, Socket } from 'socket.io-client';
import { ArrowRight, Check, Copy, Crown, MonitorPlay, Radio, Users, Zap } from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL ?? 'http://localhost:3000';
type Leader = { id: string; name: string; score: number; correct: number; rank: number; answered: number; averageTime: number };
type Question = { id: string; order: number; text: string; options: { key: string; text: string }[]; timeLimit: number; startedAt: string; endsAt: string };
let socket: Socket | undefined;
const connect = () => socket ??= io(API);

function Home() { return <main className="landing"><div className="brand-mark"><Zap size={18} fill="currentColor" /> TECHNICAL AWARENESS</div><div className="hero-grid"><section><p className="eyebrow">LIVE CLASSROOM QUIZ PLATFORM</p><h1>Make every answer<br /><em>count.</em></h1><p className="lede">A focused, fast-paced technical awareness quiz for your whole class. One room, forty questions, real-time results.</p><div className="home-actions"><a className="primary" href="/host"><MonitorPlay size={19} /> Host a quiz <ArrowRight size={17} /></a><a className="secondary" href="/join"><Users size={19} /> Join with a code</a></div></section><aside className="orbit-panel"><div className="orbit-ring"><Radio size={24} /><span>LIVE</span></div><div className="floating-stat stat-one"><strong>40</strong><span>questions</span></div><div className="floating-stat stat-two"><strong>15s</strong><span>per question</span></div><div className="floating-stat stat-three"><strong>1000</strong><span>max points</span></div></aside></div><footer><span>Built for real classrooms</span><span>•</span><span>Up to 40 players</span><span>•</span><span>Server-timed</span></footer></main> }

function Join() {
    const [codeValue, setCodeValue] = useState(''); const [name, setName] = useState(''); const [error, setError] = useState(''); const [joined, setJoined] = useState(false); const [state, setState] = useState<any>(); const [question, setQuestion] = useState<Question>(); const [selected, setSelected] = useState(''); const [time, setTime] = useState(15); const [leaders, setLeaders] = useState<Leader[]>([]); const [finished, setFinished] = useState(false);
    useEffect(() => { const s = connect(); s.on('question_started', (q: Question) => { setQuestion(q); setSelected(''); }); s.on('leaderboard_updated', setLeaders); s.on('game_finished', (r: Leader[]) => { setLeaders(r); setFinished(true); }); return () => { s.off('question_started'); s.off('leaderboard_updated'); s.off('game_finished'); }; }, []);
    useEffect(() => { if (!question) return; const tick = () => setTime(Math.max(0, Math.ceil((new Date(question.endsAt).getTime() - Date.now()) / 1000))); tick(); const id = window.setInterval(tick, 250); return () => clearInterval(id); }, [question]);
    const join = () => { setError(''); connect().emit('join_game', { gameCode: codeValue, name, reconnectToken: localStorage.getItem('quizReconnectToken') }, (result: any) => { if (result.error) return setError(result.error); setState(result.state); localStorage.setItem('quizReconnectToken', result.reconnectToken); setJoined(true); }); };
    const answer = (key: string) => { if (selected || !question || time <= 0) return; setSelected(key); connect().emit('submit_answer', { questionId: question.id, selectedKey: key }, (result: any) => { if (result.error) setError(result.error); }); };
    if (finished) return <main className="app-shell"><header className="topbar"><a className="brand" href="/"><Zap size={17} fill="currentColor" /> TECHNICAL AWARENESS</a></header><section className="results-wrap"><p className="eyebrow">SESSION COMPLETE</p><h1>Nice work, {name || 'player'}.</h1><Leaderboard leaders={leaders} /></section></main>;
    if (!joined) return <main className="app-shell centered"><a className="brand" href="/"><Zap size={17} fill="currentColor" /> TECHNICAL AWARENESS</a><section className="join-card"><p className="eyebrow">PLAYER ENTRY</p><h1>Step into the room.</h1><p className="muted">Enter the code your host shared with you.</p><label>GAME CODE<input value={codeValue} onChange={e => setCodeValue(e.target.value.toUpperCase())} placeholder="TECH42" maxLength={8} /></label><label>YOUR NAME<input value={name} onChange={e => setName(e.target.value)} placeholder="First name or nickname" maxLength={28} /></label>{error && <p className="error">{error}</p>}<button className="primary full" onClick={join}>Join quiz <ArrowRight size={17} /></button></section></main>;
    return <main className="app-shell"><header className="topbar"><a className="brand" href="/"><Zap size={17} fill="currentColor" /> TECHNICAL AWARENESS</a><span className="live-pill"><span /> Waiting room</span></header><section className="player-view">{!question ? <div className="waiting"><div className="pulse-icon"><Radio /></div><p className="eyebrow">YOU'RE IN</p><h1>Eyes on the screen,<br />{name}.</h1><p className="muted">{state?.participants?.length ?? 1} players in the room. The host will begin shortly.</p></div> : <div className="question-view"><div className="question-meta"><span>QUESTION {question.order} / 40</span><strong className={time < 5 ? 'urgent' : ''}>{time.toString().padStart(2, '0')}</strong></div><div className="timer-track"><span style={{ width: `${(time / question.timeLimit) * 100}%` }} /></div><h1>{question.text}</h1><div className="option-grid">{question.options.map(option => <button key={option.key} className={`option ${selected === option.key ? 'selected' : ''}`} onClick={() => answer(option.key)} disabled={Boolean(selected) || time === 0}><span>{option.key}</span>{option.text}</button>)}</div>{selected && <p className="submitted"><Check size={17} /> Answer submitted. Waiting for others.</p>}</div>}</section></main>;
}
function Leaderboard({ leaders }: { leaders: Leader[] }) { return <div className="leaderboard"><div className="leader-head"><span>RANKING</span><span>SCORE</span></div>{leaders.map((leader, index) => <div className={`leader-row ${index === 0 ? 'winner' : ''}`} key={leader.id}><b>{leader.rank}</b><span>{index === 0 && <Crown size={16} />} {leader.name}</span><strong>{leader.score.toLocaleString()}</strong></div>)}</div>; }

function Host() {
    const [session, setSession] = useState<any>(); const [leaders, setLeaders] = useState<Leader[]>([]); const [error, setError] = useState(''); const [question, setQuestion] = useState<Question>(); const [copied, setCopied] = useState(false); const [ended, setEnded] = useState(false); const [time, setTime] = useState(15);
    useEffect(() => { const s = connect(); s.on('question_started', setQuestion); s.on('leaderboard_updated', setLeaders); s.on('participant_joined', (participant: any) => setSession((current: any) => current ? { ...current, participants: [...current.participants.filter((item: any) => item.id !== participant.id), participant] } : current)); s.on('game_finished', (r: Leader[]) => { setLeaders(r); setEnded(true); }); return () => { s.off('question_started'); s.off('leaderboard_updated'); s.off('participant_joined'); s.off('game_finished'); }; }, []);
    const create = async () => { try { const response = await fetch(`${API}/api/sessions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ quizId: 'technical-awareness' }) }); const body = await response.text(); const data = body ? JSON.parse(body) : {}; if (!response.ok) return setError(data.error ?? 'Unable to create the live session.'); setSession(data); } catch { setError('Unable to reach the quiz server. Check that the backend is running.'); } };
    useEffect(() => { if (!question) return; const tick = () => setTime(Math.max(0, Math.ceil((new Date(question.endsAt).getTime() - Date.now()) / 1000))); tick(); const id = window.setInterval(tick, 250); return () => clearInterval(id); }, [question]);
    if (!session) return <main className="app-shell centered"><a className="brand" href="/"><Zap size={17} fill="currentColor" /> TECHNICAL AWARENESS</a><section className="host-start"><div className="host-icon"><MonitorPlay /></div><p className="eyebrow">HOST CONSOLE</p><h1>Bring your room<br />to life.</h1><p className="muted">Create a live session from the 40-question Technical Awareness quiz.</p>{error && <p className="error">{error}</p>}<button className="primary full" onClick={create}>Create live session <ArrowRight size={17} /></button></section></main>;
    const start = () => connect().emit('host_start_game', { sessionId: session.id }, (r: any) => r?.error && setError(r.error)); const next = () => connect().emit('host_next_question', { sessionId: session.id }); const end = () => connect().emit('host_end_game', { sessionId: session.id }); const copy = () => { navigator.clipboard.writeText(session.gameCode); setCopied(true); setTimeout(() => setCopied(false), 1500); };
    return <main className="app-shell host-shell"><header className="topbar"><a className="brand" href="/"><Zap size={17} fill="currentColor" /> TECHNICAL AWARENESS</a><span className="live-pill"><span /> Host console</span></header><section className="host-content"><div className="host-header"><div><p className="eyebrow">LIVE SESSION</p><h1>{question ? `Question ${question.order}` : 'Lobby'}</h1></div><div className="code-block"><small>GAME CODE</small><strong>{session.gameCode}</strong><button onClick={copy} title="Copy game code">{copied ? <Check size={17} /> : <Copy size={17} />}</button></div></div>{ended ? <><p className="eyebrow">QUIZ COMPLETE</p><h2 className="finish-title">Final ranking</h2><Leaderboard leaders={leaders} /><a className="secondary export" href={`${API}/api/sessions/${session.id}/export`}>Download CSV</a></> : question ? <div className="live-grid"><div className="live-question"><div className="question-meta"><span>QUESTION {question.order} / 40</span><strong className={time < 5 ? 'urgent' : ''}>{time.toString().padStart(2, '0')}</strong></div><div className="timer-track"><span style={{ width: `${(time / question.timeLimit) * 100}%` }} /></div><h2>{question.text}</h2><div className="host-options">{question.options.map(o => <div key={o.key}><b>{o.key}</b>{o.text}</div>)}</div><div className="host-actions"><button className="primary" onClick={next}>{question.order === 40 ? 'Finish quiz' : 'Next question'} <ArrowRight size={17} /></button><button className="danger" onClick={end}>End quiz</button></div></div><aside className="side-panel"><div className="panel-title"><span>LIVE LEADERBOARD</span><Users size={17} /></div><Leaderboard leaders={leaders} /></aside></div> : <div className="lobby"><div className="lobby-code"><span>Students join at</span><strong>/join</strong><p>Share the game code above with your class.</p></div><div className="waiting-list"><div className="panel-title"><span>CONNECTED STUDENTS</span><strong>{session.participants.length} / 40</strong></div>{session.participants.length ? session.participants.map((p: any, i: number) => <div className="student" key={p.id}><span>{String(i + 1).padStart(2, '0')}</span>{p.name}<i /></div>) : <p className="muted">Students will appear here as they join.</p>}<button className="primary full" onClick={start} disabled={!session.participants.length}>Start quiz <Radio size={17} /></button></div></div>}</section></main>;
}
function App() { const path = window.location.pathname; return path.startsWith('/host') ? <Host /> : path.startsWith('/join') ? <Join /> : <Home />; }

createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
